# versao do Compose, essa 3.9 é uma versao nova que atende os recursos que precisamos
# para rodar os containers
version: "3.9"


# lista dos containers que vão rodar.
# services é uma lista de aplicações/serviços que o Compose vai orquestrar.
# Cada item dentro de services representa um container (ou conjunto de containers) com sua configuração.
services:
#   funciona como uma label (um identificador lógico) dentro do docker-compose.yml
  analytics-service:  # ← label do serviço
    build: .
    # container_name:  → nome real do container que roda o banco.
    container_name: aanalytics-service
    ports:
      - "8005:8005"
    env_file:
      - .env
    environment :
            # Variáveis obrigatórias para AWS
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      PORT: ${PORT}
    restart: unless-stopped

    # configurado a rede de comunicação entre os serviços
    networks:
      - shared_net
  
  
# configurado a rede de comunicação entre os serviços
networks:
  shared_net:
    external: true
